# Generated by Django 3.2.5 on 2021-08-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210813_0529'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usertemp',
            table='usertemps',
        ),
    ]
