# Generated by Django 3.2.5 on 2021-08-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('ST1', '서류제출'), ('ST2', '1차면접'), ('ST3', '2차면접'), ('ST4', '합격'), ('ST5', '불합격')], default='ST1', max_length=3),
        ),
    ]
