# Generated by Django 3.2.5 on 2021-08-24 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=10)),
                ('position_title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('work_type', models.CharField(max_length=10)),
                ('career_type', models.CharField(choices=[('N', '신입'), ('C', '경력'), ('NC', '신입/경력')], default='NC', max_length=3)),
                ('job_openings', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=30)),
                ('deadline', models.DateField(default='9999-12-31')),
                ('minimum_salary', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('maximum_salary', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
            ],
            options={
                'db_table': 'recruits',
            },
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('hash_id', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'stacks',
            },
        ),
        migrations.CreateModel(
            name='RecruitStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruits.recruit')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruits.stack')),
            ],
            options={
                'db_table': 'recruits_stacks',
            },
        ),
        migrations.CreateModel(
            name='RecruitApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruits.recruit')),
            ],
            options={
                'db_table': 'recruits_applications',
            },
        ),
        migrations.AddField(
            model_name='recruit',
            name='applications',
            field=models.ManyToManyField(related_name='recruits', through='recruits.RecruitApplication', to='applications.Application'),
        ),
        migrations.AddField(
            model_name='recruit',
            name='stacks',
            field=models.ManyToManyField(related_name='recruits', through='recruits.RecruitStack', to='recruits.Stack'),
        ),
    ]
