# Generated by Django 3.2.5 on 2021-08-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruit',
            name='type',
            field=models.CharField(choices=[('N', '신입'), ('C', '경력'), ('NC', '신입/경력')], default='NC', max_length=3),
        ),
    ]
