# Generated by Django 3.2.5 on 2021-08-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0002_auto_20210809_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='maximum_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='recruit',
            name='minimum_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='deadline',
            field=models.DateField(default='9999-12-31'),
        ),
    ]
